export type ProductCategory = {
  id: number;
  name: string;
  slug: string;
};

export type ProductBrand = {
  id: number;
  name: string;
  slug?: string;
};

export type ProductItem = {
  id: number;
  urlImg: string | null;
  name: string;
  description: string | null;
  quantity: number;
  sold: number;
  category: ProductCategory;
  categoryId: number;
  brand: ProductBrand;
  brandId: number;
  originalPrice: number;
  discountPercent: number;
  currentPrice: number;
  isActive: boolean;
};

export const productList: ProductItem[] = [
  {
    id: 1,
    urlImg: "/images/products/blacktea1.jpg",
    name: "Midnight Spice",
    description:
      "Một sự pha trộn đậm đà với quế, bạch đậu khấu và chút hương đinh hương, phù hợp cho buổi sáng đầy năng lượng.",
    quantity: 40,
    sold: 15,
    category: { id: 1, name: "Trà đen", slug: "blacktea" },
    categoryId: 1,
    brand: { id: 1, name: "Tea House" },
    brandId: 1,
    originalPrice: 220000,
    discountPercent: 15,
    currentPrice: 187000,
    isActive: true,
  },
  {
    id: 2,
    urlImg: "/images/products/blacktea2.jpg",
    name: "Golden Earl",
    description:
      "Biến tấu từ Earl Grey cổ điển với hương mật ong nhẹ và hậu vị mềm mại.",
    quantity: 28,
    sold: 9,
    category: { id: 1, name: "Trà đen", slug: "blacktea" },
    categoryId: 1,
    brand: { id: 2, name: "Royal Leaf" },
    brandId: 2,
    originalPrice: 245000,
    discountPercent: 0,
    currentPrice: 245000,
    isActive: true,
  },
  {
    id: 3,
    urlImg: "/images/products/blacktea3.jpg",
    name: "Smoky Reverie",
    description:
      "Trà đen đậm đà với hương khói, thoảng vị mạch nha và chút hậu vị đất ấm.",
    quantity: 0,
    sold: 31,
    category: { id: 1, name: "Trà đen", slug: "blacktea" },
    categoryId: 1,
    brand: { id: 3, name: "Mountain Tea" },
    brandId: 3,
    originalPrice: 260000,
    discountPercent: 10,
    currentPrice: 234000,
    isActive: false,
  },
  {
    id: 4,
    urlImg: "/images/products/matcha1.jpg",
    name: "Zen Garden",
    description:
      "Matcha dịu nhẹ kết hợp với hương hoa nhài và hoa hồng, cân bằng và thanh mát.",
    quantity: 52,
    sold: 20,
    category: { id: 2, name: "Matcha", slug: "matcha" },
    categoryId: 2,
    brand: { id: 1, name: "Tea House" },
    brandId: 1,
    originalPrice: 320000,
    discountPercent: 20,
    currentPrice: 256000,
    isActive: true,
  },
  {
    id: 5,
    urlImg: "/images/products/matcha2.jpg",
    name: "Minted Harmony",
    description:
      "Matcha mượt mà hòa cùng bạc hà tươi mát, cực kỳ phù hợp cho những ngày nóng.",
    quantity: 35,
    sold: 12,
    category: { id: 2, name: "Matcha", slug: "matcha" },
    categoryId: 2,
    brand: { id: 4, name: "Green Bloom" },
    brandId: 4,
    originalPrice: 295000,
    discountPercent: 0,
    currentPrice: 295000,
    isActive: true,
  },
  {
    id: 6,
    urlImg: "/images/products/matcha5.jpg",
    name: "Matcha Choco Bliss",
    description:
      "Sự hòa quyện giữa matcha và socola cho cảm giác đậm vị nhưng vẫn thanh nhẹ.",
    quantity: 14,
    sold: 18,
    category: { id: 2, name: "Matcha", slug: "matcha" },
    categoryId: 2,
    brand: { id: 4, name: "Green Bloom" },
    brandId: 4,
    originalPrice: 340000,
    discountPercent: 12,
    currentPrice: 299200,
    isActive: true,
  },
  {
    id: 7,
    urlImg: "/images/products/oolong1.jpg",
    name: "Jade Orchid",
    description:
      "Trà ô long thơm ngát với hương hoa lan và hoa nhài tinh tế, hậu vị rất sạch.",
    quantity: 26,
    sold: 7,
    category: { id: 3, name: "Trà ô long", slug: "oolong" },
    categoryId: 3,
    brand: { id: 5, name: "Orient Leaf" },
    brandId: 5,
    originalPrice: 280000,
    discountPercent: 8,
    currentPrice: 257600,
    isActive: true,
  },
  {
    id: 8,
    urlImg: "/images/products/oolong4.jpg",
    name: "Golden Lotus",
    description:
      "Trà ô long ấm áp, hương hoa nhẹ và chút vị đào chín, phù hợp dùng mỗi chiều.",
    quantity: 22,
    sold: 11,
    category: { id: 3, name: "Trà ô long", slug: "oolong" },
    categoryId: 3,
    brand: { id: 5, name: "Orient Leaf" },
    brandId: 5,
    originalPrice: 310000,
    discountPercent: 0,
    currentPrice: 310000,
    isActive: true,
  },
  {
    id: 9,
    urlImg: "/images/products/oolong8.jpg",
    name: "Mystic Garden",
    description:
      "Trà ô long với hương đất, gỗ và lớp hương hoa thanh nhẹ như dạo bước trong vườn thiền.",
    quantity: 9,
    sold: 16,
    category: { id: 3, name: "Trà ô long", slug: "oolong" },
    categoryId: 3,
    brand: { id: 6, name: "Zen Valley" },
    brandId: 6,
    originalPrice: 355000,
    discountPercent: 18,
    currentPrice: 291100,
    isActive: true,
  },
  {
    id: 10,
    urlImg: "/images/products/whitetea1.jpg",
    name: "Silver Dew",
    description:
      "Trà trắng nhẹ nhàng với hương lê tươi mát và chút hoa nhài, cực kỳ thanh tao.",
    quantity: 18,
    sold: 5,
    category: { id: 4, name: "Trà trắng", slug: "whitetea" },
    categoryId: 4,
    brand: { id: 2, name: "Royal Leaf" },
    brandId: 2,
    originalPrice: 265000,
    discountPercent: 0,
    currentPrice: 265000,
    isActive: true,
  },
  {
    id: 11,
    urlImg: "/images/products/whitetea3.jpg",
    name: "Vanilla Snowfall",
    description:
      "Trà trắng mịn màng với hương vani và hạnh nhân nhẹ, phù hợp làm quà tặng.",
    quantity: 12,
    sold: 14,
    category: { id: 4, name: "Trà trắng", slug: "whitetea" },
    categoryId: 4,
    brand: { id: 7, name: "Pure Mist" },
    brandId: 7,
    originalPrice: 300000,
    discountPercent: 25,
    currentPrice: 225000,
    isActive: true,
  },
  {
    id: 12,
    urlImg: "/images/products/whitetea8.jpg",
    name: "Golden Sunrise",
    description:
      "Trà trắng ngọt ngào với hương trái cây nhiệt đới và chút vỏ cam chanh đầy sảng khoái.",
    quantity: 0,
    sold: 22,
    category: { id: 4, name: "Trà trắng", slug: "whitetea" },
    categoryId: 4,
    brand: { id: 7, name: "Pure Mist" },
    brandId: 7,
    originalPrice: 315000,
    discountPercent: 5,
    currentPrice: 299250,
    isActive: false,
  },
  {
    id: 13,
    urlImg: "/images/products/whitetea8.jpg",
    name: "Golden Sunrise",
    description:
      "Trà trắng ngọt ngào với hương trái cây nhiệt đới và chút vỏ cam chanh đầy sảng khoái.",
    quantity: 0,
    sold: 22,
    category: { id: 4, name: "Trà trắng", slug: "whitetea" },
    categoryId: 4,
    brand: { id: 7, name: "Pure Mist" },
    brandId: 7,
    originalPrice: 315000,
    discountPercent: 5,
    currentPrice: 299250,
    isActive: false,
  },
  {
    id: 14,
    urlImg: "/images/products/whitetea8.jpg",
    name: "Golden Sunrise",
    description:
      "Trà trắng ngọt ngào với hương trái cây nhiệt đới và chút vỏ cam chanh đầy sảng khoái.",
    quantity: 0,
    sold: 22,
    category: { id: 4, name: "Trà trắng", slug: "whitetea" },
    categoryId: 4,
    brand: { id: 7, name: "Pure Mist" },
    brandId: 7,
    originalPrice: 315000,
    discountPercent: 5,
    currentPrice: 299250,
    isActive: false,
  },
  {
    id: 15,
    urlImg: "/images/products/whitetea8.jpg",
    name: "Golden Sunrise",
    description:
      "Trà trắng ngọt ngào với hương trái cây nhiệt đới và chút vỏ cam chanh đầy sảng khoái.",
    quantity: 0,
    sold: 22,
    category: { id: 4, name: "Trà trắng", slug: "whitetea" },
    categoryId: 4,
    brand: { id: 7, name: "Pure Mist" },
    brandId: 7,
    originalPrice: 315000,
    discountPercent: 5,
    currentPrice: 299250,
    isActive: false,
  },
  {
    id: 16,
    urlImg: "/images/products/whitetea8.jpg",
    name: "Golden Sunrise",
    description:
      "Trà trắng ngọt ngào với hương trái cây nhiệt đới và chút vỏ cam chanh đầy sảng khoái.",
    quantity: 0,
    sold: 22,
    category: { id: 4, name: "Trà trắng", slug: "whitetea" },
    categoryId: 4,
    brand: { id: 7, name: "Pure Mist" },
    brandId: 7,
    originalPrice: 315000,
    discountPercent: 5,
    currentPrice: 299250,
    isActive: false,
  },
  {
    id: 17,
    urlImg: "/images/products/whitetea8.jpg",
    name: "Golden Sunrise",
    description:
      "Trà trắng ngọt ngào với hương trái cây nhiệt đới và chút vỏ cam chanh đầy sảng khoái.",
    quantity: 0,
    sold: 22,
    category: { id: 4, name: "Trà trắng", slug: "whitetea" },
    categoryId: 4,
    brand: { id: 7, name: "Pure Mist" },
    brandId: 7,
    originalPrice: 315000,
    discountPercent: 5,
    currentPrice: 299250,
    isActive: false,
  },
  {
    id: 18,
    urlImg: "/images/products/whitetea8.jpg",
    name: "Golden Sunrise",
    description:
      "Trà trắng ngọt ngào với hương trái cây nhiệt đới và chút vỏ cam chanh đầy sảng khoái.",
    quantity: 0,
    sold: 22,
    category: { id: 4, name: "Trà trắng", slug: "whitetea" },
    categoryId: 4,
    brand: { id: 7, name: "Pure Mist" },
    brandId: 7,
    originalPrice: 315000,
    discountPercent: 5,
    currentPrice: 299250,
    isActive: false,
  },
  {
    id: 19,
    urlImg: "/images/products/whitetea8.jpg",
    name: "Golden Sunrise",
    description:
      "Trà trắng ngọt ngào với hương trái cây nhiệt đới và chút vỏ cam chanh đầy sảng khoái.",
    quantity: 0,
    sold: 22,
    category: { id: 4, name: "Trà trắng", slug: "whitetea" },
    categoryId: 4,
    brand: { id: 7, name: "Pure Mist" },
    brandId: 7,
    originalPrice: 315000,
    discountPercent: 5,
    currentPrice: 299250,
    isActive: false,
  },
  {
    id: 20,
    urlImg: "/images/products/whitetea8.jpg",
    name: "Golden Sunrise",
    description:
      "Trà trắng ngọt ngào với hương trái cây nhiệt đới và chút vỏ cam chanh đầy sảng khoái.",
    quantity: 0,
    sold: 22,
    category: { id: 4, name: "Trà trắng", slug: "whitetea" },
    categoryId: 4,
    brand: { id: 7, name: "Pure Mist" },
    brandId: 7,
    originalPrice: 315000,
    discountPercent: 5,
    currentPrice: 299250,
    isActive: false,
  },
  {
    id: 21,
    urlImg: "/images/products/whitetea8.jpg",
    name: "Golden Sunrise",
    description:
      "Trà trắng ngọt ngào với hương trái cây nhiệt đới và chút vỏ cam chanh đầy sảng khoái.",
    quantity: 0,
    sold: 22,
    category: { id: 4, name: "Trà trắng", slug: "whitetea" },
    categoryId: 4,
    brand: { id: 7, name: "Pure Mist" },
    brandId: 7,
    originalPrice: 315000,
    discountPercent: 5,
    currentPrice: 299250,
    isActive: false,
  },
  {
    id: 22,
    urlImg: "/images/products/whitetea8.jpg",
    name: "Golden Sunrise",
    description:
      "Trà trắng ngọt ngào với hương trái cây nhiệt đới và chút vỏ cam chanh đầy sảng khoái.",
    quantity: 0,
    sold: 22,
    category: { id: 4, name: "Trà trắng", slug: "whitetea" },
    categoryId: 4,
    brand: { id: 7, name: "Pure Mist" },
    brandId: 7,
    originalPrice: 315000,
    discountPercent: 5,
    currentPrice: 299250,
    isActive: false,
  },
  {
    id: 23,
    urlImg: "/images/products/whitetea8.jpg",
    name: "Golden Sunrise",
    description:
      "Trà trắng ngọt ngào với hương trái cây nhiệt đới và chút vỏ cam chanh đầy sảng khoái.",
    quantity: 0,
    sold: 22,
    category: { id: 4, name: "Trà trắng", slug: "whitetea" },
    categoryId: 4,
    brand: { id: 7, name: "Pure Mist" },
    brandId: 7,
    originalPrice: 315000,
    discountPercent: 5,
    currentPrice: 299250,
    isActive: false,
  },
  {
    id: 24,
    urlImg: "/images/products/whitetea8.jpg",
    name: "Golden Sunrise",
    description:
      "Trà trắng ngọt ngào với hương trái cây nhiệt đới và chút vỏ cam chanh đầy sảng khoái.",
    quantity: 0,
    sold: 22,
    category: { id: 4, name: "Trà trắng", slug: "whitetea" },
    categoryId: 4,
    brand: { id: 7, name: "Pure Mist" },
    brandId: 7,
    originalPrice: 315000,
    discountPercent: 5,
    currentPrice: 299250,
    isActive: false,
  },
  {
    id: 25,
    urlImg: "/images/products/whitetea8.jpg",
    name: "Golden Sunrise",
    description:
      "Trà trắng ngọt ngào với hương trái cây nhiệt đới và chút vỏ cam chanh đầy sảng khoái.",
    quantity: 0,
    sold: 22,
    category: { id: 4, name: "Trà trắng", slug: "whitetea" },
    categoryId: 4,
    brand: { id: 7, name: "Pure Mist" },
    brandId: 7,
    originalPrice: 315000,
    discountPercent: 5,
    currentPrice: 299250,
    isActive: false,
  },
  {
    id: 26,
    urlImg: "/images/products/whitetea8.jpg",
    name: "Golden Sunrise",
    description:
      "Trà trắng ngọt ngào với hương trái cây nhiệt đới và chút vỏ cam chanh đầy sảng khoái.",
    quantity: 0,
    sold: 22,
    category: { id: 4, name: "Trà trắng", slug: "whitetea" },
    categoryId: 4,
    brand: { id: 7, name: "Pure Mist" },
    brandId: 7,
    originalPrice: 315000,
    discountPercent: 5,
    currentPrice: 299250,
    isActive: false,
  },
  {
    id: 27,
    urlImg: "/images/products/whitetea8.jpg",
    name: "Golden Sunrise",
    description:
      "Trà trắng ngọt ngào với hương trái cây nhiệt đới và chút vỏ cam chanh đầy sảng khoái.",
    quantity: 0,
    sold: 22,
    category: { id: 4, name: "Trà trắng", slug: "whitetea" },
    categoryId: 4,
    brand: { id: 7, name: "Pure Mist" },
    brandId: 7,
    originalPrice: 315000,
    discountPercent: 5,
    currentPrice: 299250,
    isActive: false,
  },
  {
    id: 28,
    urlImg: "/images/products/whitetea8.jpg",
    name: "Golden Sunrise",
    description:
      "Trà trắng ngọt ngào với hương trái cây nhiệt đới và chút vỏ cam chanh đầy sảng khoái.",
    quantity: 0,
    sold: 22,
    category: { id: 4, name: "Trà trắng", slug: "whitetea" },
    categoryId: 4,
    brand: { id: 7, name: "Pure Mist" },
    brandId: 7,
    originalPrice: 315000,
    discountPercent: 5,
    currentPrice: 299250,
    isActive: false,
  },
  {
    id: 29,
    urlImg: "/images/products/whitetea8.jpg",
    name: "Golden Sunrise",
    description:
      "Trà trắng ngọt ngào với hương trái cây nhiệt đới và chút vỏ cam chanh đầy sảng khoái.",
    quantity: 0,
    sold: 22,
    category: { id: 4, name: "Trà trắng", slug: "whitetea" },
    categoryId: 4,
    brand: { id: 7, name: "Pure Mist" },
    brandId: 7,
    originalPrice: 315000,
    discountPercent: 5,
    currentPrice: 299250,
    isActive: false,
  },
  {
    id: 30,
    urlImg: "/images/products/whitetea8.jpg",
    name: "Golden Sunrise",
    description:
      "Trà trắng ngọt ngào với hương trái cây nhiệt đới và chút vỏ cam chanh đầy sảng khoái.",
    quantity: 0,
    sold: 22,
    category: { id: 4, name: "Trà trắng", slug: "whitetea" },
    categoryId: 4,
    brand: { id: 7, name: "Pure Mist" },
    brandId: 7,
    originalPrice: 315000,
    discountPercent: 5,
    currentPrice: 299250,
    isActive: false,
  },
  {
    id: 31,
    urlImg: "/images/products/whitetea8.jpg",
    name: "Golden Sunrise",
    description:
      "Trà trắng ngọt ngào với hương trái cây nhiệt đới và chút vỏ cam chanh đầy sảng khoái.",
    quantity: 0,
    sold: 22,
    category: { id: 4, name: "Trà trắng", slug: "whitetea" },
    categoryId: 4,
    brand: { id: 7, name: "Pure Mist" },
    brandId: 7,
    originalPrice: 315000,
    discountPercent: 5,
    currentPrice: 299250,
    isActive: false,
  },
  {
    id: 32,
    urlImg: "/images/products/whitetea8.jpg",
    name: "Golden Sunrise",
    description:
      "Trà trắng ngọt ngào với hương trái cây nhiệt đới và chút vỏ cam chanh đầy sảng khoái.",
    quantity: 0,
    sold: 22,
    category: { id: 4, name: "Trà trắng", slug: "whitetea" },
    categoryId: 4,
    brand: { id: 7, name: "Pure Mist" },
    brandId: 7,
    originalPrice: 315000,
    discountPercent: 5,
    currentPrice: 299250,
    isActive: false,
  },
  {
    id: 33,
    urlImg: "/images/products/whitetea8.jpg",
    name: "Golden Sunrise",
    description:
      "Trà trắng ngọt ngào với hương trái cây nhiệt đới và chút vỏ cam chanh đầy sảng khoái.",
    quantity: 0,
    sold: 22,
    category: { id: 4, name: "Trà trắng", slug: "whitetea" },
    categoryId: 4,
    brand: { id: 7, name: "Pure Mist" },
    brandId: 7,
    originalPrice: 315000,
    discountPercent: 5,
    currentPrice: 299250,
    isActive: false,
  },
  {
    id: 34,
    urlImg: "/images/products/whitetea8.jpg",
    name: "Golden Sunrise",
    description:
      "Trà trắng ngọt ngào với hương trái cây nhiệt đới và chút vỏ cam chanh đầy sảng khoái.",
    quantity: 0,
    sold: 22,
    category: { id: 4, name: "Trà trắng", slug: "whitetea" },
    categoryId: 4,
    brand: { id: 7, name: "Pure Mist" },
    brandId: 7,
    originalPrice: 315000,
    discountPercent: 5,
    currentPrice: 299250,
    isActive: false,
  },
  {
    id: 35,
    urlImg: "/images/products/whitetea8.jpg",
    name: "Golden Sunrise",
    description:
      "Trà trắng ngọt ngào với hương trái cây nhiệt đới và chút vỏ cam chanh đầy sảng khoái.",
    quantity: 0,
    sold: 22,
    category: { id: 4, name: "Trà trắng", slug: "whitetea" },
    categoryId: 4,
    brand: { id: 7, name: "Pure Mist" },
    brandId: 7,
    originalPrice: 315000,
    discountPercent: 5,
    currentPrice: 299250,
    isActive: false,
  },
  {
    id: 36,
    urlImg: "/images/products/whitetea8.jpg",
    name: "Golden Sunrise",
    description:
      "Trà trắng ngọt ngào với hương trái cây nhiệt đới và chút vỏ cam chanh đầy sảng khoái.",
    quantity: 0,
    sold: 22,
    category: { id: 4, name: "Trà trắng", slug: "whitetea" },
    categoryId: 4,
    brand: { id: 7, name: "Pure Mist" },
    brandId: 7,
    originalPrice: 315000,
    discountPercent: 5,
    currentPrice: 299250,
    isActive: false,
  },
  {
    id: 37,
    urlImg: "/images/products/whitetea8.jpg",
    name: "Golden Sunrise",
    description:
      "Trà trắng ngọt ngào với hương trái cây nhiệt đới và chút vỏ cam chanh đầy sảng khoái.",
    quantity: 0,
    sold: 22,
    category: { id: 4, name: "Trà trắng", slug: "whitetea" },
    categoryId: 4,
    brand: { id: 7, name: "Pure Mist" },
    brandId: 7,
    originalPrice: 315000,
    discountPercent: 5,
    currentPrice: 299250,
    isActive: false,
  },
  {
    id: 38,
    urlImg: "/images/products/whitetea8.jpg",
    name: "Golden Sunrise",
    description:
      "Trà trắng ngọt ngào với hương trái cây nhiệt đới và chút vỏ cam chanh đầy sảng khoái.",
    quantity: 0,
    sold: 22,
    category: { id: 4, name: "Trà trắng", slug: "whitetea" },
    categoryId: 4,
    brand: { id: 7, name: "Pure Mist" },
    brandId: 7,
    originalPrice: 315000,
    discountPercent: 5,
    currentPrice: 299250,
    isActive: false,
  },
  {
    id: 39,
    urlImg: "/images/products/whitetea8.jpg",
    name: "Golden Sunrise",
    description:
      "Trà trắng ngọt ngào với hương trái cây nhiệt đới và chút vỏ cam chanh đầy sảng khoái.",
    quantity: 0,
    sold: 22,
    category: { id: 4, name: "Trà trắng", slug: "whitetea" },
    categoryId: 4,
    brand: { id: 7, name: "Pure Mist" },
    brandId: 7,
    originalPrice: 315000,
    discountPercent: 5,
    currentPrice: 299250,
    isActive: false,
  },
  {
    id: 40,
    urlImg: "/images/products/whitetea8.jpg",
    name: "Golden Sunrise",
    description:
      "Trà trắng ngọt ngào với hương trái cây nhiệt đới và chút vỏ cam chanh đầy sảng khoái.",
    quantity: 0,
    sold: 22,
    category: { id: 4, name: "Trà trắng", slug: "whitetea" },
    categoryId: 4,
    brand: { id: 7, name: "Pure Mist" },
    brandId: 7,
    originalPrice: 315000,
    discountPercent: 5,
    currentPrice: 299250,
    isActive: false,
  },
  {
    id: 41,
    urlImg: "/images/products/whitetea8.jpg",
    name: "Golden Sunrise",
    description:
      "Trà trắng ngọt ngào với hương trái cây nhiệt đới và chút vỏ cam chanh đầy sảng khoái.",
    quantity: 0,
    sold: 22,
    category: { id: 4, name: "Trà trắng", slug: "whitetea" },
    categoryId: 4,
    brand: { id: 7, name: "Pure Mist" },
    brandId: 7,
    originalPrice: 315000,
    discountPercent: 5,
    currentPrice: 299250,
    isActive: false,
  },
  {
    id: 42,
    urlImg: "/images/products/whitetea8.jpg",
    name: "Golden Sunrise",
    description:
      "Trà trắng ngọt ngào với hương trái cây nhiệt đới và chút vỏ cam chanh đầy sảng khoái.",
    quantity: 0,
    sold: 22,
    category: { id: 4, name: "Trà trắng", slug: "whitetea" },
    categoryId: 4,
    brand: { id: 7, name: "Pure Mist" },
    brandId: 7,
    originalPrice: 315000,
    discountPercent: 5,
    currentPrice: 299250,
    isActive: false,
  },
  {
    id: 43,
    urlImg: "/images/products/whitetea8.jpg",
    name: "Golden Sunrise",
    description:
      "Trà trắng ngọt ngào với hương trái cây nhiệt đới và chút vỏ cam chanh đầy sảng khoái.",
    quantity: 0,
    sold: 22,
    category: { id: 4, name: "Trà trắng", slug: "whitetea" },
    categoryId: 4,
    brand: { id: 7, name: "Pure Mist" },
    brandId: 7,
    originalPrice: 315000,
    discountPercent: 5,
    currentPrice: 299250,
    isActive: false,
  },
  {
    id: 44,
    urlImg: "/images/products/whitetea8.jpg",
    name: "Golden Sunrise",
    description:
      "Trà trắng ngọt ngào với hương trái cây nhiệt đới và chút vỏ cam chanh đầy sảng khoái.",
    quantity: 0,
    sold: 22,
    category: { id: 4, name: "Trà trắng", slug: "whitetea" },
    categoryId: 4,
    brand: { id: 7, name: "Pure Mist" },
    brandId: 7,
    originalPrice: 315000,
    discountPercent: 5,
    currentPrice: 299250,
    isActive: false,
  },
  {
    id: 45,
    urlImg: "/images/products/whitetea8.jpg",
    name: "Golden Sunrise",
    description:
      "Trà trắng ngọt ngào với hương trái cây nhiệt đới và chút vỏ cam chanh đầy sảng khoái.",
    quantity: 0,
    sold: 22,
    category: { id: 4, name: "Trà trắng", slug: "whitetea" },
    categoryId: 4,
    brand: { id: 7, name: "Pure Mist" },
    brandId: 7,
    originalPrice: 315000,
    discountPercent: 5,
    currentPrice: 299250,
    isActive: false,
  },
  {
    id: 46,
    urlImg: "/images/products/whitetea8.jpg",
    name: "Golden Sunrise",
    description:
      "Trà trắng ngọt ngào với hương trái cây nhiệt đới và chút vỏ cam chanh đầy sảng khoái.",
    quantity: 0,
    sold: 22,
    category: { id: 4, name: "Trà trắng", slug: "whitetea" },
    categoryId: 4,
    brand: { id: 7, name: "Pure Mist" },
    brandId: 7,
    originalPrice: 315000,
    discountPercent: 5,
    currentPrice: 299250,
    isActive: false,
  },
  {
    id: 47,
    urlImg: "/images/products/whitetea8.jpg",
    name: "Golden Sunrise",
    description:
      "Trà trắng ngọt ngào với hương trái cây nhiệt đới và chút vỏ cam chanh đầy sảng khoái.",
    quantity: 0,
    sold: 22,
    category: { id: 4, name: "Trà trắng", slug: "whitetea" },
    categoryId: 4,
    brand: { id: 7, name: "Pure Mist" },
    brandId: 7,
    originalPrice: 315000,
    discountPercent: 5,
    currentPrice: 299250,
    isActive: false,
  },
  {
    id: 48,
    urlImg: "/images/products/whitetea8.jpg",
    name: "Golden Sunrise",
    description:
      "Trà trắng ngọt ngào với hương trái cây nhiệt đới và chút vỏ cam chanh đầy sảng khoái.",
    quantity: 0,
    sold: 22,
    category: { id: 4, name: "Trà trắng", slug: "whitetea" },
    categoryId: 4,
    brand: { id: 7, name: "Pure Mist" },
    brandId: 7,
    originalPrice: 315000,
    discountPercent: 5,
    currentPrice: 299250,
    isActive: false,
  },
  {
    id: 49,
    urlImg: "/images/products/whitetea8.jpg",
    name: "Golden Sunrise",
    description:
      "Trà trắng ngọt ngào với hương trái cây nhiệt đới và chút vỏ cam chanh đầy sảng khoái.",
    quantity: 0,
    sold: 22,
    category: { id: 4, name: "Trà trắng", slug: "whitetea" },
    categoryId: 4,
    brand: { id: 7, name: "Pure Mist" },
    brandId: 7,
    originalPrice: 315000,
    discountPercent: 5,
    currentPrice: 299250,
    isActive: false,
  },
  {
    id: 50,
    urlImg: "/images/products/whitetea8.jpg",
    name: "Golden Sunrise",
    description:
      "Trà trắng ngọt ngào với hương trái cây nhiệt đới và chút vỏ cam chanh đầy sảng khoái.",
    quantity: 0,
    sold: 22,
    category: { id: 4, name: "Trà trắng", slug: "whitetea" },
    categoryId: 4,
    brand: { id: 7, name: "Pure Mist" },
    brandId: 7,
    originalPrice: 315000,
    discountPercent: 5,
    currentPrice: 299250,
    isActive: false,
  },
  {
    id: 51,
    urlImg: "/images/products/whitetea8.jpg",
    name: "Golden Sunrise",
    description:
      "Trà trắng ngọt ngào với hương trái cây nhiệt đới và chút vỏ cam chanh đầy sảng khoái.",
    quantity: 0,
    sold: 22,
    category: { id: 4, name: "Trà trắng", slug: "whitetea" },
    categoryId: 4,
    brand: { id: 7, name: "Pure Mist" },
    brandId: 7,
    originalPrice: 315000,
    discountPercent: 5,
    currentPrice: 299250,
    isActive: false,
  },
  {
    id: 52,
    urlImg: "/images/products/whitetea8.jpg",
    name: "Golden Sunrise",
    description:
      "Trà trắng ngọt ngào với hương trái cây nhiệt đới và chút vỏ cam chanh đầy sảng khoái.",
    quantity: 0,
    sold: 22,
    category: { id: 4, name: "Trà trắng", slug: "whitetea" },
    categoryId: 4,
    brand: { id: 7, name: "Pure Mist" },
    brandId: 7,
    originalPrice: 315000,
    discountPercent: 5,
    currentPrice: 299250,
    isActive: false,
  },
  {
    id: 53,
    urlImg: "/images/products/whitetea8.jpg",
    name: "Golden Sunrise",
    description:
      "Trà trắng ngọt ngào với hương trái cây nhiệt đới và chút vỏ cam chanh đầy sảng khoái.",
    quantity: 0,
    sold: 22,
    category: { id: 4, name: "Trà trắng", slug: "whitetea" },
    categoryId: 4,
    brand: { id: 7, name: "Pure Mist" },
    brandId: 7,
    originalPrice: 315000,
    discountPercent: 5,
    currentPrice: 299250,
    isActive: false,
  },
  {
    id: 54,
    urlImg: "/images/products/whitetea8.jpg",
    name: "Golden Sunrise",
    description:
      "Trà trắng ngọt ngào với hương trái cây nhiệt đới và chút vỏ cam chanh đầy sảng khoái.",
    quantity: 0,
    sold: 22,
    category: { id: 4, name: "Trà trắng", slug: "whitetea" },
    categoryId: 4,
    brand: { id: 7, name: "Pure Mist" },
    brandId: 7,
    originalPrice: 315000,
    discountPercent: 5,
    currentPrice: 299250,
    isActive: false,
  },
  {
    id: 55,
    urlImg: "/images/products/whitetea8.jpg",
    name: "Golden Sunrise",
    description:
      "Trà trắng ngọt ngào với hương trái cây nhiệt đới và chút vỏ cam chanh đầy sảng khoái.",
    quantity: 0,
    sold: 22,
    category: { id: 4, name: "Trà trắng", slug: "whitetea" },
    categoryId: 4,
    brand: { id: 7, name: "Pure Mist" },
    brandId: 7,
    originalPrice: 315000,
    discountPercent: 5,
    currentPrice: 299250,
    isActive: false,
  },
  {
    id: 56,
    urlImg: "/images/products/whitetea8.jpg",
    name: "Golden Sunrise",
    description:
      "Trà trắng ngọt ngào với hương trái cây nhiệt đới và chút vỏ cam chanh đầy sảng khoái.",
    quantity: 0,
    sold: 22,
    category: { id: 4, name: "Trà trắng", slug: "whitetea" },
    categoryId: 4,
    brand: { id: 7, name: "Pure Mist" },
    brandId: 7,
    originalPrice: 315000,
    discountPercent: 5,
    currentPrice: 299250,
    isActive: false,
  },
  {
    id: 57,
    urlImg: "/images/products/whitetea8.jpg",
    name: "Golden Sunrise",
    description:
      "Trà trắng ngọt ngào với hương trái cây nhiệt đới và chút vỏ cam chanh đầy sảng khoái.",
    quantity: 0,
    sold: 22,
    category: { id: 4, name: "Trà trắng", slug: "whitetea" },
    categoryId: 4,
    brand: { id: 7, name: "Pure Mist" },
    brandId: 7,
    originalPrice: 315000,
    discountPercent: 5,
    currentPrice: 299250,
    isActive: false,
  },
  {
    id: 58,
    urlImg: "/images/products/whitetea8.jpg",
    name: "Golden Sunrise",
    description:
      "Trà trắng ngọt ngào với hương trái cây nhiệt đới và chút vỏ cam chanh đầy sảng khoái.",
    quantity: 0,
    sold: 22,
    category: { id: 4, name: "Trà trắng", slug: "whitetea" },
    categoryId: 4,
    brand: { id: 7, name: "Pure Mist" },
    brandId: 7,
    originalPrice: 315000,
    discountPercent: 5,
    currentPrice: 299250,
    isActive: false,
  },
  {
    id: 59,
    urlImg: "/images/products/whitetea8.jpg",
    name: "Golden Sunrise",
    description:
      "Trà trắng ngọt ngào với hương trái cây nhiệt đới và chút vỏ cam chanh đầy sảng khoái.",
    quantity: 0,
    sold: 22,
    category: { id: 4, name: "Trà trắng", slug: "whitetea" },
    categoryId: 4,
    brand: { id: 7, name: "Pure Mist" },
    brandId: 7,
    originalPrice: 315000,
    discountPercent: 5,
    currentPrice: 299250,
    isActive: false,
  },
  {
    id: 60,
    urlImg: "/images/products/whitetea8.jpg",
    name: "Golden Sunrise",
    description:
      "Trà trắng ngọt ngào với hương trái cây nhiệt đới và chút vỏ cam chanh đầy sảng khoái.",
    quantity: 0,
    sold: 22,
    category: { id: 4, name: "Trà trắng", slug: "whitetea" },
    categoryId: 4,
    brand: { id: 7, name: "Pure Mist" },
    brandId: 7,
    originalPrice: 315000,
    discountPercent: 5,
    currentPrice: 299250,
    isActive: false,
  },
  {
    id: 61,
    urlImg: "/images/products/whitetea8.jpg",
    name: "Golden Sunrise",
    description:
      "Trà trắng ngọt ngào với hương trái cây nhiệt đới và chút vỏ cam chanh đầy sảng khoái.",
    quantity: 0,
    sold: 22,
    category: { id: 4, name: "Trà trắng", slug: "whitetea" },
    categoryId: 4,
    brand: { id: 7, name: "Pure Mist" },
    brandId: 7,
    originalPrice: 315000,
    discountPercent: 5,
    currentPrice: 299250,
    isActive: false,
  },
  {
    id: 62,
    urlImg: "/images/products/whitetea8.jpg",
    name: "Golden Sunrise",
    description:
      "Trà trắng ngọt ngào với hương trái cây nhiệt đới và chút vỏ cam chanh đầy sảng khoái.",
    quantity: 0,
    sold: 22,
    category: { id: 4, name: "Trà trắng", slug: "whitetea" },
    categoryId: 4,
    brand: { id: 7, name: "Pure Mist" },
    brandId: 7,
    originalPrice: 315000,
    discountPercent: 5,
    currentPrice: 299250,
    isActive: false,
  },
  {
    id: 63,
    urlImg: "/images/products/whitetea8.jpg",
    name: "Golden Sunrise",
    description:
      "Trà trắng ngọt ngào với hương trái cây nhiệt đới và chút vỏ cam chanh đầy sảng khoái.",
    quantity: 0,
    sold: 22,
    category: { id: 4, name: "Trà trắng", slug: "whitetea" },
    categoryId: 4,
    brand: { id: 7, name: "Pure Mist" },
    brandId: 7,
    originalPrice: 315000,
    discountPercent: 5,
    currentPrice: 299250,
    isActive: false,
  },
  {
    id: 64,
    urlImg: "/images/products/whitetea8.jpg",
    name: "Golden Sunrise",
    description:
      "Trà trắng ngọt ngào với hương trái cây nhiệt đới và chút vỏ cam chanh đầy sảng khoái.",
    quantity: 0,
    sold: 22,
    category: { id: 4, name: "Trà trắng", slug: "whitetea" },
    categoryId: 4,
    brand: { id: 7, name: "Pure Mist" },
    brandId: 7,
    originalPrice: 315000,
    discountPercent: 5,
    currentPrice: 299250,
    isActive: false,
  },
  {
    id: 65,
    urlImg: "/images/products/whitetea8.jpg",
    name: "Golden Sunrise",
    description:
      "Trà trắng ngọt ngào với hương trái cây nhiệt đới và chút vỏ cam chanh đầy sảng khoái.",
    quantity: 0,
    sold: 22,
    category: { id: 4, name: "Trà trắng", slug: "whitetea" },
    categoryId: 4,
    brand: { id: 7, name: "Pure Mist" },
    brandId: 7,
    originalPrice: 315000,
    discountPercent: 5,
    currentPrice: 299250,
    isActive: false,
  },
];

export const partnerLogoBasePath = "/images/partner-logos/";
export const partnerLogos = [
  { fileName: "costco.png", alt: "Costco Logo" },
  { fileName: "kroger.png", alt: "Kroger Logo" },
  { fileName: "meijer.png", alt: "Meijer Logo" },
  { fileName: "publix.png", alt: "Publix Logo" },
  { fileName: "safeway.png", alt: "Safeway Logo" },
  { fileName: "target.png", alt: "Target Logo" },
  { fileName: "walmart.png", alt: "Walmart Logo" },
  { fileName: "wegmans.png", alt: "Wegmans Logo" },
  { fileName: "whole-foods.png", alt: "Whole Foods Logo" },
];